[project]
name = "r2framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.139.2",
    "psycopg2>=2.9.12",
    "sqlmodel>=0.0.39",
    "strands-agents[openai,otel]>=1.50.2",
    "strands-agents-tools>=0.8.5",
    "pillow>=12.3.0",
    "numpy>=2.5.1",
    "scikit-image>=0.25.2",
    "opencv-python>=5.0.0.93",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "alembic>=1.18.5",
    "aioboto3>=7.0.0",
    "scalar-fastapi>=1.4.3",
    "pytest-cov>=7.0.0",
    "opentelemetry-instrumentation-fastapi>=0.65b0",
    "bcrypt>=5.0.0",
]

[dependency-groups]
dev = [
    "bandit>=1.9.3",
    "basedpyright>=1.39.9",
    "ruff>=0.15.22",
]
temp = [
    "opencv-python>=5.0.0.93",
    "scikit-image>=0.25.2",
]

[tool.bandit]
exclude_dirs = ["tests", "migrations"]

[tool.basedpyright]
exclude = ["**/migrations", "**/.*", "**/__pycache__", "**/tests/unit/shared"]
reportMissingTypeStubs = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportAny = false
reportExplicitAny = false
reportUnannotatedClassAttribute = false
reportImportCycles = "warning"
reportCallInDefaultInitializer = false
